name: kalii

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TALESCALE_AUTH_KEY }}

      - name: Install XFCE Desktop & VNC
        run: |
          sudo apt update
          sudo apt install xfce4 xfce4-goodies tightvncserver git -y
          mkdir -p ~/.vnc
          echo "12345678" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          echo "#!/bin/bash" > ~/.vnc/xstartup
          echo "xrdb \$HOME/.Xresources" >> ~/.vnc/xstartup
          echo "startxfce4 &" >> ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          vncserver :1 -geometry 1280x720 -depth 24

      - name: Launch noVNC Web Server
        run: |
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify ~/noVNC/utils/websockify
          nohup ~/noVNC/utils/launch.sh --vnc localhost:5901 --listen 6080 &
          sleep 5
          echo "=========================================="
          echo "Your Tailscale IP is: $(tailscale ip -4)"
          echo "=========================================="
          sleep 21600
          
